### ISSUE TITLE
KAS 1.2 update breaks flex o pipes

### ISSUE THREAD

**Issue by menachg** [UmbraSpaceIndustries/MKS#1452] opened 2019-04-12 17:52 UTC
when updating to kas 1.2 flex o pip will keep parts connected but the options to link/unlink will disappear in the part's functionality

**Comment by JacobRoth** [comment] 2019-04-13 18:57
I just experienced this as well. Also the pipes themselves are now invisible - still connecting the vessels but the graphics disappeared.

**Comment by menachg** [comment] 2019-04-13 18:59
actually I observed the pipe disappearing behavior before and they still worked fine so and I don't think it's related to the kas 1.2 update

**Comment by tjdeckard** [comment] 2020-10-11 00:56
Duplicate of #1461

**Closed by tjdeckard** 2020-10-11 00:56 UTC
