### ISSUE TITLE
Blizzy toolbar icons are magenta

### ISSUE THREAD

**Issue by stub42** [UmbraSpaceIndustries/MKS#944] opened 2016-10-17 05:01 UTC
I added the MKS buttons to blizzy toolbar (latest, for 1.2). They display as bright magenta rectangles, which is not what they used to do.

**Comment by tarheel1999** [comment] 2016-10-18 14:33
The toolbar wrapper has the image location hard-coded and needs to be changed to reflect the new folder structure, i.e. from Kolonization to MKS.  I don't know if anything else needs to be done to make it work properly.

**Comment by LeLeon** [comment] 2016-10-19 01:47
Same here. On Toolbar the both USI icons appear purple (blank). Tested on almost USI-only and also on more modded state. Tried on existing career and on a fresh sandbox game.

Logs, pics.
https://drive.google.com/file/d/0B6IfqHC0fCsFUlJaNm5zR05Mdlk/view

**Comment by LeLeon** [comment] 2016-10-19 22:57
My quickfix.
I created folder within gamedata/USI with the name "Kolonization". There i copied the 8 .png files (beginning with Kolony, Orbital, Plan, Station) of the MKS folder. Blank toolbar icons gone until it is fixed in MKS.

**Comment by brustmopf** [comment] 2017-01-01 18:24
It's a really quick fix in the code. For the sake of simplicity and tidiness of repository I hope, it can get fixed without actually having to do a pull request...

**Comment by fat-lobyte** [comment] 2017-03-02 15:08
Duplicate of #1035 and fixed in Pull Request #1102.

**Closed** 2017-04-22 20:58 UTC
