### ISSUE TITLE
how to fix flex-o-tube not working with kis 1.2

### ISSUE THREAD

**Issue by ryancoates321** [UmbraSpaceIndustries/MKS#1461] opened 2019-07-02 23:09 UTC
I'm running 1.7.2 on steam I can't link flex-o-tubes togeather kis nor kas? can someone help me fix this I love this mod

**Comment by Ihmosky** [comment] 2019-07-03 04:03
> I'm running 1.7.2 on steam I can't link flex-o-tubes togeather kis nor kas? can someone help me fix this I love this mod

i dont know.I think it is due to the KAS's changing.

**Comment by MagentaRex** [comment] 2019-07-16 01:32
The issue is the lack of a module in the flex-o-tube CFG to make it able to connect. 
just compare the current KAS tube files to the current flex tube one. Making it basically a glorified light bulb.

**Comment by Sinuisan** [comment] 2019-08-03 02:37
So I've run into this bug aswell - when you say 'compare the KAS tube files' I'm confused - do I need to add an entry to a CFG file to get the mods to recognise the parts?

Or is this something KAS needs to patch in future builds?

**Comment by ryancoates321** [comment] 2019-08-03 14:22
Well I'm script my self so I fixed if you want let me know

**Comment by Sinuisan** [comment] 2019-08-03 15:10
Yup. I've found the forum thread - sounds like it's a problem from KAS.

If you have a fix I'd love to have it!

**Comment by ryancoates321** [comment] 2019-08-03 15:19
https://drive.google.com/open?id=1ytQ9E3lNlfcaCo5KeRcpSFLML7MkOoab

**Comment by ryancoates321** [comment] 2019-08-03 15:20
Let me know if it works

**Comment by Sinuisan** [comment] 2019-08-03 16:26
Ok so I dumped that folder into my gamedata and overwrite everything. 

Initial testing seems to work - will do some more thorough testing later this evening. 

THANKYOU SO MUCH.

**Comment by ryancoates321** [comment] 2019-08-03 16:26
Your welcome

**Comment by ryancoates321** [comment] 2019-08-03 16:30
Let me know what I can improve

**Comment by Sinuisan** [comment] 2019-08-04 00:08
So some weird stuff - it appears a few times on the research panel, and when you go to connect one tube to another its not doing the 'normal' pipe connection "link". You select A and then select B that is in range. 

Will attach images tomorrow.

**Comment by ryancoates321** [comment] 2019-08-04 01:02
Okay

**Comment by Sinuisan** [comment] 2019-08-07 20:37
Okay - sorry for the delay in getting this over. Not had much time to play. 

<img width="1280" alt="KSP Flexotube bug" src="https://user-images.githubusercontent.com/25729205/62655783-a5b7eb80-b95a-11e9-9d3f-2ab675a9de5e.png">
<img width="1280" alt="KSP Flexotube bug 2" src="https://user-images.githubusercontent.com/25729205/62655914-f62f4900-b95a-11e9-9014-bda1f07b6b57.png">

As shown - it appears 118 times in the "meta materials" research tab, this didn't happen before adding your files, so something is interacting weirdly. 
The only other bug I've found is that its listed 3 times as "carried by kerbals". Same thing is happening for other items such as the 'Ranger' modules. Not sure if that happened previously as I only just unlocked. 

Full mod list - 
[Mods.txt](https://github.com/UmbraSpaceIndustries/MKS/files/3478800/Mods.txt)

Not sure if that mod list is aware of what version of MKS etc I'm running as this is after I've merged your files into my gamedata directory.

**Comment by ryancoates321** [comment] 2019-08-07 21:43
what version are u running and I will look into it

**Comment by Sinuisan** [comment] 2019-08-08 18:24
CKAN 1.26.2
KSP 1.7.3.2594 (latest release build on steam)

Mods all up to date on CKAN.

**Comment by ryancoates321** [comment] 2019-08-09 00:12
Ok same as me

**Comment by ryancoates321** [comment] 2019-08-09 15:27
@Sinuisan it has something to do with KIS not me

**Closed** 2022-03-14 01:18 UTC
