### ISSUE TITLE
Flex-O-Tubes not working

### ISSUE THREAD

**Issue by tomplant** [UmbraSpaceIndustries/MKS#1459] opened 2019-05-21 22:19 UTC
Hi, I have upgraded things to the latest and greatest. Running KSP 1.7.0.2483 with KIS 1.21, KAS 1.3, MKS 1.1.0.0 and for the life of me, I can't seem to get the Flex-O-Tubes to work.

I've scoured the wiki, searched forums, google searched, but I can't seem to find anyone reporting an issue, or doing anything wrong. This worked with 1.7.0 and with earlier Mods, so I'm just curious has the Flex-O-Tubes been made legacy or something?
Thanks!

**Comment by Ihmosky** [comment] 2019-06-09 10:27
1.4.1 is ok.1.6.1 gets the same bug.

**Comment by JBHann** [comment] 2019-08-10 20:14
Flex-O-Tubes rely upon the pipes from KAS as a dependency. However, pipe functionality in KAS was deprecated and finally removed from newer versions of KAS starting KAS 1.2. As a work-around you can **downgrade your KAS version to 1.1** to make Flex-O-Tubes work.

A more permanent fix will require MKS to directly incorporate the pipe functionality to remove the dependency or otherwise change how flex-O-tubes work/dependency.

**Comment by tjdeckard** [comment] 2020-10-11 00:56
Duplicate of #1461

**Closed by tjdeckard** 2020-10-11 00:56 UTC
