### ISSUE TITLE
re consider having the number of crew on board affects ship hub

### ISSUE THREAD

**Issue by danielboro** [UmbraSpaceIndustries/MKS#1302] opened 2017-07-06 07:57 UTC
Unlike supplies, in hub the size of the crew on board determines the ships hub time value
This means that when the crew on board is bigger than the crew affected by multi the ships hub time drops and as a result kerbal hub time plummets
See numbers in Example

Ship has 108 hub from 10*(5.2+5.2+0.2+0.2) (crew affected 4,4,1,1)

crew size | 1 | 2 | 3 | 4 | 5 | 6
ship hub | 108 | 106 | 105.3333 | 105 | 21.6 | 18
kerbal hub | 108 | 53 | 35.11111 | 26.25 | 4.32 | 3

**Comment by theRagingIrishman** [comment] 2017-07-06 08:21
No. It is intended that having more kerbals inside the same amount of space will reduce each kerbals habtimes and this is not something that will change. If I am misunderstanding you, please comment again and I'll reopen this but I'm closing it for now.

**Comment by theRagingIrishman** [comment] 2017-07-06 08:22
Also, this should have gone on the USI-LS github repo as hab time is a LS mechanic

**Closed by theRagingIrishman** 2017-07-06 08:21 UTC

**Comment by BobPalmer** [comment] 2017-07-06 08:48
Also adding 'No' as this is by design.
